source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'spring',        group: :development
gem 'responders'
gem 'active_model_serializers'

group :development, :test do
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end
